#!/bin/bash

echo "Namespace,Deployment,Replicas,Liveness,Readiness,CPU Limits,Memory Limits,HPA"

namespaces=$(kubectl get ns -o jsonpath='{.items[*].metadata.name}')

for ns in $namespaces; do
  deployments=$(kubectl get deploy -n $ns -o jsonpath='{.items[*].metadata.name}')
  for deploy in $deployments; do
    replicas=$(kubectl get deploy $deploy -n $ns -o jsonpath='{.spec.replicas}')
    liveness=$(kubectl get deploy $deploy -n $ns -o jsonpath='{.spec.template.spec.containers[*].livenessProbe.httpGet.path}')
    readiness=$(kubectl get deploy $deploy -n $ns -o jsonpath='{.spec.template.spec.containers[*].readinessProbe.httpGet.path}')
    cpu_limits=$(kubectl get deploy $deploy -n $ns -o jsonpath='{.spec.template.spec.containers[*].resources.limits.cpu}')
    memory_limits=$(kubectl get deploy $deploy -n $ns -o jsonpath='{.spec.template.spec.containers[*].resources.limits.memory}')
    hpa=$(kubectl get hpa -n $ns -o jsonpath="{.items[?(@.spec.scaleTargetRef.name=='$deploy')].spec}")
    if [ -z "$hpa" ]; then hpa="None"; fi
    echo "$ns,$deploy,$replicas,$liveness,$readiness,$cpu_limits,$memory_limits,$hpa"
  done
done
